### ISSUE TITLE
PlatformIO released their framework with 5.3.0

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1728]
### The Feature

We should consider migrating to that one, maybe it helps for some open framebuffer, ... issues.

See https://github.com/platformio/platform-espressif32/releases/tag/v5.3.0

**Comment by caco3** [comment]
I tried to build with it but failed during linking:
```
/home/xxx/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/esp32cam/esp-idf/jomjol_wlan/libjomjol_wlan.a(connect_wlan.o):(.literal._ZL24esp_bss_rssi_low_handlerPvPKciS_+0x1c): undefined reference to `esp_rrm_send_neighbor_rep_request'
/home/xxx/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/esp32cam/esp-idf/jomjol_wlan/libjomjol_wlan.a(connect_wlan.o):(.literal._ZL24esp_bss_rssi_low_handlerPvPKciS_+0x20): undefined reference to `esp_wnm_send_bss_transition_mgmt_query'
/home/xxx/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/esp32cam/esp-idf/jomjol_wlan/libjomjol_wlan.a(connect_wlan.o): in function `esp_bss_rssi_low_handler(void*, char const*, int, void*)':
/home/xxx/temp/AI-on-the-edge-device/code/components/jomjol_wlan/connect_wlan.cpp:286: undefined reference to `esp_rrm_send_neighbor_rep_request'
/home/xxx/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/xxx/temp/AI-on-the-edge-device/code/components/jomjol_wlan/connect_wlan.cpp:289: undefined reference to `esp_wnm_send_bss_transition_mgmt_query'
/home/xxx/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/esp32cam/esp-idf/jomjol_wlan/libjomjol_wlan.a(connect_wlan.o): in function `neighbor_report_recv_cb(void*, unsigned char const*, unsigned int)':
/home/xxx/temp/AI-on-the-edge-device/code/components/jomjol_wlan/connect_wlan.cpp:256: undefined reference to `esp_wnm_send_bss_transition_mgmt_query'
```

Odly, looking for `esp_rrm_send_neighbor_rep_request` still is used in the latest examples, so I don't think it got removed in IDF [4.4.3](https://github.com/espressif/esp-idf/releases/tag/v4.4.3) (which is part of the PlatformIO Framework 5.3.0...

**Comment by jomjol** [comment]
I just locally compiled it with a single change in `plattformio.ini`:

```
[env:esp32cam]
platform = espressif32@5.3.0
board = esp32cam
;board = m5stack-core-esp32
framework = espidf
```

It is working and I had a full run - although without meaningfull result on my table :-)

**Comment by caco3** [comment]
hmm, that is odd.

Do those parameters match sour settings?
```
PACKAGES: 
 - framework-espidf @ 3.40403.0 (4.4.3) 
 - tool-cmake @ 3.16.4 
 - tool-esptoolpy @ 1.40400.0 (4.4.0) 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
```

> It is working and I had a full run - although without meaningfull result on my table :-)

That's what the demo mode is for :)

**Comment by jomjol** [comment]
Sorry, just went back to v5.2.0 to work on the softAP, will check this tomorrow.

**Comment by caco3** [comment]
The build server shows the same issue as my local build: https://github.com/jomjol/AI-on-the-edge-device/actions/runs/3809214367

So I would suggest to keep this aside for now.

**Comment by jomjol** [comment]
Just checked again. Those are my settings:
```
rocessing esp32cam (platform: espressif32@5.3.0; board: esp32cam; framework: espidf)
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32cam.html
PLATFORM: Espressif 32 (5.3.0) > AI Thinker ESP32-CAM
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf @ 3.40403.0 (4.4.3)
 - tool-cmake @ 3.16.4
 - tool-esptoolpy @ 1.40400.0 (4.4.0)
 - tool-idf @ 1.0.1
 - tool-mconf @ 1.4060000.20190628 (406.0.0)
 - tool-ninja @ 1.9.0
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
```

That's the output:
```
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Linking .pio\build\esp32cam\firmware.elf
Retrieving maximum program size .pio\build\esp32cam\firmware.elf
Checking size .pio\build\esp32cam\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  20.0% (used 65668 bytes from 327680 bytes)
Flash: [========= ]  88.3% (used 1718441 bytes from 1945600 bytes)
Building .pio\build\esp32cam\firmware.bin
esptool.py v4.4
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.

```

I use the current rolling from yesterday evening. But attention: I have modified my sdkonfig.esp32cam to reduce the firmware size.

**Comment by nliaudat** [comment]
with platformio/espressif32 @ _**5.2.0** with **5.3 dependencies**_
```
platform = platformio/espressif32 @ 5.2.0
platform_packages = 
; platformio/espressif32 @ 5.3.0 dependencies : 
    platformio/framework-espidf @ 3.40403.0
    platformio/tool-cmake @ 3.16.4
    platformio/tool-esptoolpy@^1.40400.0
    platformio/tool-idf @ 1.0.1
    platformio/tool-mconf @ 1.4060000.20190628
    platformio/tool-ninja @ 1.9.0
    espressif/toolchain-esp32ulp @ 2.35.0-20220830
    espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
```

espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
makes compile fatal errors : 

```
/jomjol_wlan/libjomjol_wlan.a(connect_wlan.o):(.literal._ZL24esp_bss_rssi_low_handlerPvPKciS_+0x1c): undefined reference to `esp_rrm_send_neighbor_rep_request'
/jomjol_wlan/libjomjol_wlan.a(connect_wlan.o):(.literal._ZL24esp_bss_rssi_low_handlerPvPKciS_+0x20): undefined reference to `esp_wnm_send_bss_transition_mgmt_query'
/jomjol_wlan/libjomjol_wlan.a(connect_wlan.o): in function `esp_bss_rssi_low_handler(void*, char const*, int, void*)':
/jomjol_wlan/connect_wlan.cpp:286: undefined reference to `esp_rrm_send_neighbor_rep_request'
/jomjol_wlan/connect_wlan.cpp:289: undefined reference to `esp_wnm_send_bss_transition_mgmt_query'
/jomjol_wlan/libjomjol_wlan.a(connect_wlan.o): in function `neighbor_report_recv_cb(void*, unsigned char const*, unsigned int)':
/jomjol_wlan/connect_wlan.cpp:256: undefined reference to `esp_wnm_send_bss_transition_mgmt_query'
```

**Comment by caco3** [comment]
So you see the same linker errors as I did and also the Github Actions Build System had.

**Comment by Slider0007** [comment]
> So you see the same linker errors as I did and also the Github Actions Build System had.

I also see the same errors when trying to build with 5.3.0

**Comment by caco3** [comment]
[PlatformIO 6.0.0](https://github.com/platformio/platform-espressif32/releases/tag/v6.0.0) just got released, but I did not test it yet.

**Comment by caco3** [comment]
I did a quick test, it seems to look better now. Still compiler errors, but they all look like they could be solved.

**Comment by caco3** [comment]
done
